name: iOS Build & TestFlight Upload

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 1'  # every Monday at 3 AM (UTC)
  workflow_dispatch:      # allows manual run

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Resolve Swift Packages
        run: xcodebuild -resolvePackageDependencies

      - name: Build for Simulator
        run: xcodebuild clean build -scheme "Xsite Broker" -destination 'platform=iOS Simulator,name=iPhone 17 Pro'

      - name: Archive for Release
        run: xcodebuild -scheme "Xsite Broker" -archivePath build/XsiteBroker.xcarchive archive

      - name: Export IPA
        run: xcodebuild -exportArchive \
          -archivePath build/XsiteBroker.xcarchive \
          -exportPath build/ipa \
          -exportOptionsPlist ExportOptions.plist

      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: build/ipa/XsiteBroker.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ name: iOS Build & TestFlight Upload

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 1'  # every Monday at 3 AM (UTC)
  workflow_dispatch:      # allows manual run

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Resolve Swift Packages
        run: xcodebuild -resolvePackageDependencies

      - name: Build for Simulator
        run: xcodebuild clean build -scheme "Xsite Broker" -destination 'platform=iOS Simulator,name=iPhone 17 Pro'

      - name: Archive for Release
        run: xcodebuild -scheme "Xsite Broker" -archivePath build/XsiteBroker.xcarchive archive

      - name: Export IPA
        run: xcodebuild -exportArchive \
          -archivePath build/XsiteBroker.xcarchive \
          -exportPath build/ipa \
          -exportOptionsPlist ExportOptions.plist

      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: build/ipa/XsiteBroker.ipa
          issuer-id: ${{ 964974c3-189c-4839-aeff-713d9428c5c5 }}
          api-key-id: ${{ UWSRAN8L72 }}
          api-private-key: ${{ -----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg5Hcy/2KofeTH4m5v
Xix0JThoP2iD7bvp3sVb9eF+qhWgCgYIKoZIzj0DAQehRANCAAT83+OENlCKXVxu
ECgU4Zm46xqjXhfIWfEteDnbH3dSWDNjU4MisbNALJPD99R3pxjt6MMFGeSB27GV
1JLbpMbw-----END PRIVATE KEY----- }}
